DROP TABLE IF EXISTS TBL_MESSAGE_QUEUE;

CREATE TABLE TBL_MESSAGE_QUEUE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  queue_name VARCHAR2(20) NOT NULL,
  queue_message VARCHAR2(250) NOT NULL,
  created_date  VARCHAR2(30) NOT NULL,
  receive_message CHAR(1) NOT NULL,
  created_by VARCHAR(50) DEFAULT NULL
);